a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
d0 = (a * d) - (b * c)
d1 = (e * d) - (b * f)
d2 = (a * f) - (e * c)
print(d1 / d0, d2 / d0)
